spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    # Si se desea usar rutas manuales, tenemos esta opcion para usar
    # routes:
    #   - id: song-service
    #     uri: lb://song-service
    #     predicates:
    #       - Path=/songs/**
    #   - id: playlist-service
    #     uri: lb://playlist-service
    #     predicates:
    #       - Path=/playlists/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081
